
# Site settings
locale: "en"
title: "Dermi — Dermatology Clinic"
subtitle: "Healthy skin, clear answers."
description: "Dermatology blog and clinic in Bucharest. Articles, treatments, and skincare recommendations."
url: "https://dermi.ro"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "mint"  # fresh, medical feel

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 6
paginate_path: /blog/page:num/

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Author
author:
  name: "Dr. Dermi"
  avatar: "/assets/images/avatar.png"
  bio: "Board-certified dermatologist. Evidence-based skincare and dermatology updates."
  location: "Bucharest"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:contact@dermi.ro"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

# Collections
collections:
  pages:
    output: true

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Navigation
include:
  - _pages

# Exclude
exclude: ["README.md", "netlify.toml", "Gemfile", "Gemfile.lock"]

# SEO tag
logo: "/assets/images/logo-dermi.png"

# Social sharing image
image: "/assets/images/og-image.png"
