
locale: ro
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: mint
url: https://dermi.ro
baseurl: ''
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
paginate: 6
paginate_path: /blog/pagina:num/
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
include: [_pages]
logo: /assets/images/logo-dermi.png
image: /assets/images/og-image.png
title: 'Dermi — Dermatologie'
subtitle: 'Sănătate pentru pielea ta.'
description: 'Blog de dermatologie și pagină de prezentare.'
author:
  name: 'Dr. Dermi'
  avatar: '/assets/images/avatar.png'
  bio: 'Medic dermatolog.'
  location: 'București'
collections:
  pages:
    output: true
defaults:
  - scope: {path: '', type: posts}
    values: {layout: single, author_profile: true, read_time: true, comments: false, share: true, related: true}
  - scope: {path: '_pages', type: pages}
    values: {layout: single, author_profile: true}
