// Runs after `astro build`.
//
// 1. Gives every Markdown twin (/blog/<slug>.md) its own header rule — Cloudflare's _headers
//    placeholders can't match "<slug>.md" inside one path segment, and a broad /blog/* rule would
//    shadow these, so each file gets an exact rule. The Link header marks the HTML as canonical.
// 2. Redirects the old Jekyll article URLs (2025) to their new home. A published article gets a
//    permanent 301; an article that is still a draft gets a temporary 302 to /blog/ so the old URL
//    never ends in a 404 — and switches to 301 automatically once the article is published.
import { readdirSync, readFileSync, appendFileSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';

const site = 'https://dermi.ro';
const dist = resolve(import.meta.dirname, '../dist');
const blog = join(dist, 'blog');
if (!existsSync(dist)) process.exit(0);

// ── 0. Never publish placeholders: a published article must not contain "[TODO" ───────
const todo = existsSync(blog) ? readdirSync(blog).filter(f => f.endsWith('.md'))
  .filter(f => readFileSync(join(blog, f), 'utf8').includes('[TODO')) : [];
if (todo.length && process.env.PREVIEW_DRAFTS !== '1') {
  console.error(`postbuild: published article(s) still contain [TODO …] placeholders: ${todo.join(', ')}`);
  process.exit(1);
}

// ── 1. Markdown twins ──────────────────────────────────────────────────
const mdFiles = existsSync(blog) ? readdirSync(blog).filter(f => f.endsWith('.md')) : [];
const headerRules = mdFiles.map(f => {
  const slug = f.slice(0, -3);
  return `/blog/${f}\n  Content-Type: text/markdown; charset=utf-8\n  Access-Control-Allow-Origin: *\n  X-Robots-Tag: noindex\n  Link: <${site}/blog/${slug}/>; rel="canonical"\n`;
});
if (headerRules.length) {
  appendFileSync(join(dist, '_headers'), `\n# Generated by scripts/postbuild.mjs\n${headerRules.join('')}`);
}

// ── 2. Old Jekyll URLs (/:categories/:year/:month/:day/:title/) ─────────
// Live URLs as indexed in August 2025 (most posts had no parsed category, so no prefix).
const OLD_POSTS = {
  'cum-alegi-crema-hidratanta-potrivita':   ['skincare'],
  'cum-previi-petele-pigmentare':           ['skincare'],
  'cum-tratezi-rozaceea':                   ['dermatologie'],
  'ghid-complet-despre-acid-hialuronic':    ['skincare'],
  'importanta-exfolierii':                  ['skincare'],
  'mituri-despre-acnee':                    ['dermatologie'],
  'rutina-corecta-pentru-pielea-sensibila': ['skincare'],
  'spf-pe-scurt':                           ['skincare'],
  'top-5-greseli-in-ingrijirea-pielii':     ['skincare'],
};

const lines = [];
let live = 0;
for (const [slug, cats] of Object.entries(OLD_POSTS)) {
  const published = existsSync(join(blog, slug, 'index.html'));
  const [to, code] = published ? [`/blog/${slug}/`, 301] : ['/blog/', 302];
  if (published) live++;
  for (const prefix of ['', ...cats.map(c => `/${c}`)]) {
    const from = `${prefix}/2025/08/21/${slug}`;
    lines.push(`${from}/ ${to} ${code}`, `${from} ${to} ${code}`);
  }
}
// Splat rules go last (Cloudflare handles static rules first, and faster)
lines.push('/blog/pagina* /blog/ 301');
appendFileSync(join(dist, '_redirects'), `\n# Old Jekyll article URLs — generated by scripts/postbuild.mjs\n${lines.join('\n')}\n`);

console.log(`postbuild: ${headerRules.length} Markdown header rule(s); ${Object.keys(OLD_POSTS).length} old URLs redirected (${live} to published articles)`);
